### ISSUE TITLE
Epic: Ocean-lib-js Incentives

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#132]
Update the platform (contracts, JS, PY libs) to support both Balancer flows:
 -  “use Balancer core capabilities directly”; 
 -  “simple-as-possible for end user”. Therefore not just a separate driver, but easy to use via Ocean lib.
- Beta quality. At minimum, happy path unit tests for each method. >0 system-level tests.

 -  [X] Built balancer core lib-js - alpha
 - [X] Built balancer core lib-py - alpha
 - [X] Built ocean-contracts incentives alpha
 - [X] Built ocean-lib-py incentives alpha
 - [X] Built ocean-lib-js incentives alpha
 - [x] Built ocean-contracts incentives beta
 - [x] Built ocean-lib-py incentives beta
 - [x] Built ocean-lib-js incentives beta
