### ISSUE TITLE
Epic: Build lib-js Datatokens Alpha/Phase1

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#42]
Phase1 specs high level:
- [x] Quickstart e2e test [simple flow](https://github.com/oceanprotocol/lib-js/blob/feature/cleaning/README_simpleflow.md)
- [x] Quickstart e2e test [marketplace flow](https://github.com/oceanprotocol/lib-js/blob/feature/cleaning/README_simpleflow.md) 
- [x] At least one integration test using rinkeby
-  NOT yet “everything guaranteed end-to-end for L3 marketplace”. Including: ok if DT transfer is done manually from Alice to Bob
-  NOT yet compute-to-data
- Alpha quality
