### ISSUE TITLE
Epic: Build lib-js Phase2

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#55]
Beta-specs high level:
- [ ] Beta quality: “Features & DX what it should look like in production” but not hardened yet
- [ ] 100% coverage in unit tests.  (https://github.com/oceanprotocol/lib-js/issues/45)
- [ ] Integration tests / travis-CI.  (https://github.com/oceanprotocol/lib-js/issues/44)
- [ ] Deployed as appropriate to pypi/npm, maybe ethpm (https://github.com/oceanprotocol/lib-js/issues/48)
- [ ] Usable docs (docs.oceanprotocol.com, related is https://site.oceanprotocol.now.sh/developers), in a non-confusing place (e.g. clearly for v3, clearly beta) (https://github.com/oceanprotocol/lib-js/issues/46)
- [ ] Adding compute interface (https://github.com/oceanprotocol/lib-js/issues/58) 
- [ ] Has the functionality needed such that Ocean Market works end-to-end (e.g. reuse what squid-js uses. This includes compute interface, Aquarius).
