### ISSUE TITLE
Epic: Build lib-js Datatokens Beta

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#59]
Beta-specs high level:
- Beta quality: “Features & DX what it should look like in production” but not hardened yet
- [x] 70% coverage in unit tests.  (#45)
- [x] Integration tests / travis-CI.  (#44)
- [x] Deployed as appropriate to pypi/npm, maybe ethpm (#48)
- [x] Usable docs (docs.oceanprotocol.com, related is https://site.oceanprotocol.now.sh/developers), in a non-confusing place (e.g. clearly for v3, clearly beta) (#46)
- [x] Adding compute interface (#58) 
- [x] Has the functionality needed such that Ocean Market works end-to-end (e.g. reuse what squid-js uses. This includes compute interface, Aquarius). (#60)
